<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>royale-bot</artifactId>
    <version>1.0.0</version>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <robocode.version>0.38.0</robocode.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>dev.robocode.tankroyale</groupId>
            <artifactId>bot-api</artifactId>
            <version>${robocode.version}</version>
        </dependency>
    </dependencies>
</project>
